In [48]:
import pandas as pd
import numpy as np
import os
from pathlib import Path

# Get paths
BASE_DIR = Path(os.path.abspath('')).resolve().parent
PROCESSED_PATH = BASE_DIR / "data" / "processed" / "cleaned_stroke_data.csv"
OUTPUT_PATH = BASE_DIR / "outputs" / "eda_summary" / "basic_stats.csv"

# Show processed data
df = pd.read_csv(PROCESSED_PATH)
df

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,gender_Male,gender_Other,ever_married_Yes,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Urban,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,67.0,0,1,228.69,36.600000,1,1,0,1,0,1,0,0,1,1,0,0
1,61.0,0,0,202.21,28.893237,1,0,0,1,0,0,1,0,0,0,1,0
2,80.0,0,1,105.92,32.500000,1,1,0,1,0,1,0,0,0,0,1,0
3,49.0,0,0,171.23,34.400000,1,0,0,1,0,1,0,0,1,0,0,1
4,79.0,1,0,174.12,24.000000,1,0,0,1,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,80.0,1,0,83.75,28.893237,0,0,0,1,0,1,0,0,1,0,1,0
5106,81.0,0,0,125.20,40.000000,0,0,0,1,0,0,1,0,1,0,1,0
5107,35.0,0,0,82.99,30.600000,0,0,0,1,0,0,1,0,0,0,1,0
5108,51.0,0,0,166.29,25.600000,0,1,0,1,0,1,0,0,0,1,0,0
5109,44.0,0,0,85.28,26.200000,0,0,0,1,0,0,0,0,1,0,0,0

In [49]:
# Attributes for EDA
attrs = ['age', 'avg_glucose_level', 'bmi']

rows = []
for attr in attrs:
    rows.append([
        attr, 
        df[attr].mean(), 
        df[attr].median(), 
        df[attr].mode().values, 
        df[attr].max(),
        df[attr].min(),
        df[attr].std(), 
        df[attr].var()])

# Show summary data
sdf = pd.DataFrame(rows, columns=['Attribute', 'Mean', 'Median', 'Mode', 'Maximum', 'Minimum', 'Standard Deviation', 'Variance'])
sdf

,Attribute,Mean,Median,Mode,Maximum,Minimum,Standard Deviation,Variance
0,age,43.226614,45.000,[78.0],82.00,0.08,22.612647,511.331792
1,avg_glucose_level,106.147677,91.885,[93.88],271.74,55.12,45.283560,2050.600820
2,bmi,28.893237,28.400,[28.893236911794663],97.60,10.30,7.698018,59.259478

In [50]:
# Export summary to CSV
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
sdf.to_csv(OUTPUT_PATH)